dist: xenial
language: python

stages:
  - test
  - deploy

install:
  - pip install -r requirements.txt

script:
  - sh ./.tests/unit_test.sh

jobs:
  include:
    - stage: test
      script:
        - sh ./.tests/unit_test.sh
      python:
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8-dev"
    - stage: deploy
      script: 
        - sh ./.deploy.sh
      python:
        - "3.7"
      if: branch = development
