dist: xenial
language: python

before_install:
  - sudo apt-get update

install:
  - pip install -r requirements.txt

stages:
  - unit_test
  - deploy

jobs:
  include:
    - stage: unit_test
      script:
        - sh ./.tests/unit_test.sh
      python:
        - "3.5"
        - "3.6"
        - "3.7"
        - "3.8-dev"
    - stage: deploy
      script: 
        - sh ./.deploy.sh
      python:
        - "3.7"
      if: branch = development
