name: deploy-gh-pages

# Only run this when the master branch changes
on:
  push:
    branches:
    - stable

# This job installs dependencies, builds the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Install dependencies
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r dev-requirements.txt

    # Build the book
    - name: Build the project
      run: |
        sphinx-build doc html
        #TODO build and push to pypi


    # Push the HTML to github-pages
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/
        force_orphan: true
